apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ktjoqnz2p-nodejs
  janus-idp.io/tekton: ktjoqnz2p-nodejs
  backstage.io/kubernetes-id: ktjoqnz2p-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ktjoqnz2p-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
